// ======================================================
// PORT ST. LUCIE SOFTBALL LEAGUE DATA
// ======================================================
// This file contains the information displayed throughout
// the website.
//
// When updating the league, most schedule/team changes
// should be made here rather than in the HTML files.
// ======================================================

const leagueData = {
  // ==================================================
  // ANNOUNCEMENTS
  // ==================================================

  announcements: [
    {
      date: "Sep 24, 2026",
      text: "Wednesday games are canceled due to field conditions.",
    },

    {
      date: "Sep 18, 2026",
      text: "Fall league playoffs begin Monday, October 12th.",
    },

    {
      date: "Sep 15, 2026",
      text: "Field 2 will be under maintenance next Friday. Coed games moved to Field 3.",
    },
  ],

  // ==================================================
  // TEAMS
  // ==================================================

  teams: {
    mens: {
      lower: [],

      middle: [],

      upper: [
        "Clippers",
        "Las AvisPas",
        "Latin Stars",
        "Saints",
        "Son Of Pitches",
        "Stone Decor/Seatow",
        "Powerhouse",
        "Venom",
      ],
    },

    coed: {
      social: [
        "Elev8",
        "Half Nuts",
        "Halleujah Hooligans",
        "Lefty's",
        "Saints",
        "Team Challenger",
        "Killer Pineapples",
        "Crown Jewels",
        "Lefty's/Kim",
        "We Got The Run",
        "Brew Jays",
        "Tomorrow We Hurt",
        "St Lucie Hospital Heroes",
        "Smash Bros",
      ],

      lower: [],

      middleUpper: [],
    },
  },

  // ==================================================
  // GAMES / SCHEDULE
  // ==================================================
  //
  // Each game follows this format:
  //
  // {
  //     date: "Jan 5",
  //     day: "Mon",
  //     time: "6:30 PM",
  //     league: "mens",
  //     division: "Upper",
  //     away: "Team A",
  //     home: "Team B",
  //     location: "SHC 1"
  // }
  //
  // Men's divisions:
  // Lower, Middle, Upper
  //
  // Coed divisions:
  // Social, Lower, Middle/Upper
  // ==================================================

  games: [
    // ==================================================
    // MEN'S UPPER
    // Monday / Wednesday Adult Upper Winter League 2026
    // ==================================================

    {
      date: "2026-09-21",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Powerhouse",
      location: "SHC 3",
    },
    {
      date: "2026-09-21",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Stone Decor/Seatow",
      home: "Saints",
      location: "SHC 2",
    },
    {
      date: "2026-09-21",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Las AvisPas",
      location: "SHC 3",
    },
    {
      date: "2026-09-21",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Son Of Pitches",
      location: "SHC 3",
    },

    {
      date: "2026-09-23",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },
    {
      date: "2026-09-23",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Powerhouse",
      home: "Son Of Pitches",
      location: "SHC 2",
    },
    {
      date: "2026-09-23",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Latin Stars",
      location: "SHC 3",
    },
    {
      date: "2026-09-23",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Clippers",
      location: "SHC 3",
    },

    {
      date: "2026-09-28",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Son Of Pitches",
      location: "SHC 3",
    },
    {
      date: "2026-09-28",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Powerhouse",
      location: "SHC 2",
    },
    {
      date: "2026-09-28",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Stone Decor/Seatow",
      home: "Clippers",
      location: "SHC 3",
    },
    {
      date: "2026-09-28",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Las AvisPas",
      location: "SHC 3",
    },

    {
      date: "2026-09-30",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Powerhouse",
      home: "Saints",
      location: "SHC 3",
    },
    {
      date: "2026-09-30",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Venom",
      location: "SHC 2",
    },
    {
      date: "2026-09-30",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Latin Stars",
      location: "SHC 3",
    },
    {
      date: "2026-09-30",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },

    {
      date: "2026-10-05",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Powerhouse",
      location: "SHC 3",
    },
    {
      date: "2026-10-05",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Saints",
      location: "SHC 2",
    },
    {
      date: "2026-10-05",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Son Of Pitches",
      location: "SHC 3",
    },
    {
      date: "2026-10-05",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Stone Decor/Seatow",
      home: "Las AvisPas",
      location: "SHC 3",
    },

    {
      date: "2026-10-07",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Powerhouse",
      home: "Venom",
      location: "SHC 3",
    },
    {
      date: "2026-10-07",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Latin Stars",
      location: "SHC 2",
    },
    {
      date: "2026-10-07",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Clippers",
      location: "SHC 3",
    },
    {
      date: "2026-10-07",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },

    {
      date: "2026-10-12",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Powerhouse",
      location: "SHC 3",
    },
    {
      date: "2026-10-12",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Saints",
      location: "SHC 2",
    },
    {
      date: "2026-10-12",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Stone Decor/Seatow",
      home: "Venom",
      location: "SHC 3",
    },
    {
      date: "2026-10-12",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Las AvisPas",
      location: "SHC 3",
    },

    {
      date: "2026-10-14",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Son Of Pitches",
      location: "SHC 3",
    },
    {
      date: "2026-10-14",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Clippers",
      location: "SHC 2",
    },
    {
      date: "2026-10-14",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Powerhouse",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },
    {
      date: "2026-10-14",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Latin Stars",
      location: "SHC 3",
    },

    {
      date: "2026-10-19",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Saints",
      location: "SHC 3",
    },
    {
      date: "2026-10-19",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Venom",
      location: "SHC 2",
    },
    {
      date: "2026-10-19",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },
    {
      date: "2026-10-19",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Powerhouse",
      location: "SHC 3",
    },

    {
      date: "2026-10-21",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Venom",
      location: "SHC 3",
    },
    {
      date: "2026-10-21",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Stone Decor/Seatow",
      location: "SHC 2",
    },
    {
      date: "2026-10-21",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Saints",
      location: "SHC 3",
    },
    {
      date: "2026-10-21",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Clippers",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },

    {
      date: "2026-10-26",
      day: "Mon",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Powerhouse",
      location: "SHC 3",
    },
    {
      date: "2026-10-26",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Latin Stars",
      home: "Clippers",
      location: "SHC 2",
    },
    {
      date: "2026-10-26",
      day: "Mon",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Stone Decor/Seatow",
      home: "Son Of Pitches",
      location: "SHC 3",
    },
    {
      date: "2026-10-26",
      day: "Mon",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Venom",
      home: "Las AvisPas",
      location: "SHC 3",
    },

    {
      date: "2026-10-28",
      day: "Wed",
      time: "6:30 PM",
      league: "mens",
      division: "Upper",
      away: "Powerhouse",
      home: "Clippers",
      location: "SHC 3",
    },
    {
      date: "2026-10-28",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Saints",
      home: "Venom",
      location: "SHC 2",
    },
    {
      date: "2026-10-28",
      day: "Wed",
      time: "7:40 PM",
      league: "mens",
      division: "Upper",
      away: "Son Of Pitches",
      home: "Latin Stars",
      location: "SHC 3",
    },
    {
      date: "2026-10-28",
      day: "Wed",
      time: "8:50 PM",
      league: "mens",
      division: "Upper",
      away: "Las AvisPas",
      home: "Stone Decor/Seatow",
      location: "SHC 3",
    },

    // ==================================================
    // COED SOCIAL
    // Friday Coed Social Division 2026
    // ==================================================

    {
      date: "2026-09-25",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Half Nuts",
      home: "Killer Pineapples",
      location: "Lyngate",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Elev8",
      home: "We Got The Run",
      location: "SHC 1",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Smash Bros",
      home: "Tomorrow We Hurt",
      location: "Lyngate",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Brew Jays",
      home: "Saints",
      location: "SHC 1",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's",
      home: "Lefty's/Kim",
      location: "SHC 2",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Tomorrow We Hurt",
      home: "Brew Jays",
      location: "Lyngate",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "St Lucie Hospital Heroes",
      home: "Halleujah Hooligans",
      location: "SHC 1",
    },
    {
      date: "2026-09-25",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Crown Jewels",
      home: "Team Challenger",
      location: "SHC 2",
    },

    {
      date: "2026-10-02",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Killer Pineapples",
      home: "We Got The Run",
      location: "Lyngate",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Tomorrow We Hurt",
      home: "Half Nuts",
      location: "SHC 1",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Halleujah Hooligans",
      home: "Elev8",
      location: "Lyngate",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Smash Bros",
      home: "Brew Jays",
      location: "SHC 1",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's/Kim",
      home: "Crown Jewels",
      location: "SHC 1",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Halleujah Hooligans",
      home: "Lefty's",
      location: "Lyngate",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Team Challenger",
      home: "Saints",
      location: "SHC 1",
    },
    {
      date: "2026-10-02",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's",
      home: "St Lucie Hospital Heroes",
      location: "SHC 2",
    },

    {
      date: "2026-10-09",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Smash Bros",
      home: "Lefty's",
      location: "Lyngate",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Crown Jewels",
      home: "Tomorrow We Hurt",
      location: "SHC 1",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Elev8",
      home: "Team Challenger",
      location: "Lyngate",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Half Nuts",
      home: "Halleujah Hooligans",
      location: "SHC 1",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Brew Jays",
      home: "We Got The Run",
      location: "SHC 2",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Elev8",
      home: "Half Nuts",
      location: "Lyngate",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Saints",
      home: "Killer Pineapples",
      location: "SHC 1",
    },
    {
      date: "2026-10-09",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "St Lucie Hospital Heroes",
      home: "Lefty's/Kim",
      location: "SHC 2",
    },

    {
      date: "2026-10-16",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "We Got The Run",
      home: "Saints",
      location: "Lyngate",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Halleujah Hooligans",
      home: "Smash Bros",
      location: "SHC 1",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Saints",
      home: "Crown Jewels",
      location: "Lyngate",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Team Challenger",
      home: "Half Nuts",
      location: "SHC 1",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's",
      home: "Brew Jays",
      location: "SHC 2",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's/Kim",
      home: "Crown Jewels",
      location: "Lyngate",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Killer Pineapples",
      home: "Elev8",
      location: "SHC 1",
    },
    {
      date: "2026-10-16",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Tomorrow We Hurt",
      home: "St Lucie Hospital Heroes",
      location: "SHC 2",
    },

    {
      date: "2026-10-23",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "St Lucie Hospital Heroes",
      home: "Smash Bros",
      location: "Lyngate",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Brew Jays",
      home: "Killer Pineapples",
      location: "SHC 1",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "We Got The Run",
      home: "St Lucie Hospital Heroes",
      location: "Lyngate",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Elev8",
      home: "Tomorrow We Hurt",
      location: "SHC 1",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Half Nuts",
      home: "Lefty's/Kim",
      location: "SHC 2",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "We Got The Run",
      home: "Team Challenger",
      location: "Lyngate",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Crown Jewels",
      home: "Lefty's",
      location: "SHC 1",
    },
    {
      date: "2026-10-23",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Saints",
      home: "Halleujah Hooligans",
      location: "SHC 2",
    },

    {
      date: "2026-10-30",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Halleujah Hooligans",
      home: "Smash Bros",
      location: "Lyngate",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Saints",
      home: "Elev8",
      location: "SHC 1",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Team Challenger",
      home: "St Lucie Hospital Heroes",
      location: "Lyngate",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Killer Pineapples",
      home: "Crown Jewels",
      location: "SHC 1",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Tomorrow We Hurt",
      home: "Lefty's",
      location: "SHC 2",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Team Challenger",
      home: "Lefty's",
      location: "Lyngate",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's/Kim",
      home: "Brew Jays",
      location: "SHC 1",
    },
    {
      date: "2026-10-30",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "We Got The Run",
      home: "Half Nuts",
      location: "SHC 2",
    },

    {
      date: "2026-11-06",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Crown Jewels",
      home: "We Got The Run",
      location: "Lyngate",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "6:30 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's",
      home: "Halleujah Hooligans",
      location: "SHC 2",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "St Lucie Hospital Heroes",
      home: "Killer Pineapples",
      location: "Lyngate",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Brew Jays",
      home: "Elev8",
      location: "SHC 1",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "7:40 PM",
      league: "coed",
      division: "Social",
      away: "Smash Bros",
      home: "Team Challenger",
      location: "SHC 2",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Killer Pineapples",
      home: "Smash Bros",
      location: "Lyngate",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Half Nuts",
      home: "Saints",
      location: "SHC 1",
    },
    {
      date: "2026-11-06",
      day: "Fri",
      time: "8:50 PM",
      league: "coed",
      division: "Social",
      away: "Lefty's/Kim",
      home: "Tomorrow We Hurt",
      location: "SHC 2",
    },
  ],
  standings: [],
};
